version: '3.7'

volumes:
  pg-data:

services:
  db:
    image: postgres:alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: super-sekret
    volumes:
      - pg-data:/var/lib/postgresql/data
